// Central tool registry — shared source of truth for Home, Layout, search, favorites.
import {
  Search, ShieldAlert, QrCode, FileText, Activity, Calendar,
  TrendingUp, Percent, Tag, CaseSensitive, Shuffle, X,
  Zap, Lock, Smartphone, Gift, ChevronRight, Award, ClipboardList, Receipt,
  // PDF Tools icons
  Layers, Scissors, Minimize2, FileCode, FileOutput, FileImage,
  Image, RotateCcw, Unlock, ShieldCheck,
  // Image Tools icons
  Maximize2, Crop, ArrowLeftRight, Images, Stamp,
  LayoutGrid, Pipette, Focus,
  // New tool icons
  Flame, Dumbbell, Baby, Heart, DollarSign, Landmark, Coins, Lightbulb,
  ShoppingBag, Utensils, CalendarDays, CheckSquare, ListTodo, Clipboard, Star,
  BookOpen, Replace, Filter, ArrowUpDown, StickyNote, FileText as FileText2,
  Code, Binary, Link2, Shield, Fingerprint,
  // Writing Generators + Fun & Lifestyle icons
  Briefcase, Megaphone, Sparkles, AtSign, Target, Mail, Cake, CalendarHeart,
  Send, Feather, MessageCircle, Wand2, Laugh, Scale, MessageSquare,
  Snowflake, Brain, ListChecks,
  // Sprint — Branding, Marketing, Writing V2, Utility V2 icons
  Clapperboard, Mic, BookText, BookMarked, MessagesSquare, GraduationCap,
  FileSignature, Newspaper, Palette, Paintbrush, Type, LayoutTemplate,
  Contact, ImagePlus, PanelTop, Share2, Package, MailOpen, MousePointerClick,
  CalendarRange, PenLine, ScanLine, Barcode, ScanBarcode, PenTool, Pen,
  Hash, FileCheck, CreditCard,
} from 'lucide-react';
import { LucideIcon } from 'lucide-react';

export type Category = 'Text Tools' | 'Calculators' | 'Utility Tools' | 'Developer Tools' | 'PDF Tools' | 'Image Tools' | 'Daily Life' | 'Writing Generators' | 'Fun & Lifestyle' | 'Branding & Design' | 'Marketing Tools';

export interface Tool {
  title: string;
  description: string;
  icon: LucideIcon;
  href: string;
  category: Category;
  popular?: boolean;
  isNew?: boolean;
  /** Search synonym keywords — matched after title, before description. */
  tags?: string[];
}

export const TOOLS: Tool[] = [
  {
    title: 'Password Generator',
    description: 'Create strong, secure passwords with custom length and character sets.',
    icon: ShieldAlert,
    href: '/password-generator',
    category: 'Utility Tools',
    popular: true,
  },
  {
    title: 'QR Code Generator',
    description: 'Turn any URL or text into a scannable QR code instantly.',
    icon: QrCode,
    href: '/qr-code-generator',
    category: 'Developer Tools',
    popular: true,
    tags: ['qr', 'qrcode', 'scan', 'link', 'barcode'],
  },
  {
    title: 'Word Counter',
    description: 'Count words, characters, sentences, and reading time live.',
    icon: FileText,
    href: '/word-counter',
    category: 'Text Tools',
    popular: true,
  },
  {
    title: 'BMI Calculator',
    description: 'Calculate your Body Mass Index in metric or imperial units.',
    icon: Activity,
    href: '/bmi-calculator',
    category: 'Calculators',
    popular: true,
    tags: ['bmi', 'body mass', 'weight', 'health', 'fitness', 'calculator'],
  },
  {
    title: 'Age Calculator',
    description: 'Find your exact age in years, months, and days with next birthday countdown.',
    icon: Calendar,
    href: '/age-calculator',
    category: 'Calculators',
  },
  {
    title: 'Loan Calculator',
    description: 'Calculate monthly payments, total interest, and an amortization schedule.',
    icon: TrendingUp,
    href: '/loan-calculator',
    category: 'Calculators',
  },
  {
    title: 'Percentage Calculator',
    description: 'Four percentage modes — portions, ratios, change, and decrease.',
    icon: Percent,
    href: '/percentage-calculator',
    category: 'Calculators',
  },
  {
    title: 'Discount Calculator',
    description: 'Find the final price, savings, and optional sales tax on any deal.',
    icon: Tag,
    href: '/discount-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Text Case Converter',
    description: 'Convert text to UPPERCASE, lowercase, Title Case, Sentence case, and more.',
    icon: CaseSensitive,
    href: '/text-case-converter',
    category: 'Text Tools',
    isNew: true,
  },
  {
    title: 'Random Number Generator',
    description: 'Generate random numbers within any range, with history and no-duplicate mode.',
    icon: Shuffle,
    href: '/random-number-generator',
    category: 'Utility Tools',
    isNew: true,
  },
  {
    title: 'Certificate Generator',
    description: 'Design professional certificates for courses, events, competitions, and more.',
    icon: Award,
    href: '/certificate-generator',
    category: 'Utility Tools',
    isNew: true,
    tags: ['certificate', 'award', 'diploma', 'pdf', 'generator'],
  },
  {
    title: 'Resume Builder',
    description: 'Build a professional resume with 5 templates, live preview, and PDF download.',
    icon: ClipboardList,
    href: '/resume-builder',
    category: 'Utility Tools',
    isNew: true,
    tags: ['resume', 'cv', 'curriculum vitae', 'job', 'career', 'pdf', 'job application', 'work'],
  },
  {
    title: 'Invoice Generator',
    description: 'Create professional invoices with 5 templates, live preview, and PDF export.',
    icon: Receipt,
    href: '/invoice-generator',
    category: 'Utility Tools',
    isNew: true,
    tags: ['invoice', 'billing', 'receipt', 'pdf', 'payment', 'generator', 'freelance'],
  },
  // ── PDF Tools ──────────────────────────────────────────────────────────────
  {
    title: 'PDF Merge',
    description: 'Combine multiple PDF files into one — drag, reorder, and download.',
    icon: Layers,
    href: '/pdf-merge',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'PDF Split',
    description: 'Extract pages or split a PDF into multiple files by range.',
    icon: Scissors,
    href: '/pdf-split',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'PDF Compressor',
    description: 'Reduce PDF file size while keeping it readable — no server upload.',
    icon: Minimize2,
    href: '/pdf-compressor',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'Word to PDF',
    description: 'Convert DOCX files to PDF with formatting preserved — in your browser.',
    icon: FileCode,
    href: '/word-to-pdf',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'PDF to Word',
    description: 'Extract text from PDF and download as an editable Word document.',
    icon: FileOutput,
    href: '/pdf-to-word',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'JPG to PDF',
    description: 'Combine one or more images into a single PDF — drag to reorder.',
    icon: FileImage,
    href: '/jpg-to-pdf',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'PDF to JPG',
    description: 'Convert PDF pages into high-quality JPG images — download all as ZIP.',
    icon: Image,
    href: '/pdf-to-jpg',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'Rotate PDF',
    description: 'Rotate selected or all PDF pages 90°, 180°, or 270° and download.',
    icon: RotateCcw,
    href: '/rotate-pdf',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'Unlock PDF',
    description: 'Remove password protection from a PDF — you must know the password.',
    icon: Unlock,
    href: '/unlock-pdf',
    category: 'PDF Tools',
    isNew: true,
  },
  {
    title: 'Protect PDF',
    description: 'Add password protection and permissions to your PDF files.',
    icon: ShieldCheck,
    href: '/protect-pdf',
    category: 'PDF Tools',
    isNew: true,
  },
  // ── Image Tools ────────────────────────────────────────────────────────────
  {
    title: 'Image Compressor',
    description: 'Reduce image file size with adjustable compression — before & after preview.',
    icon: Minimize2,
    href: '/image-compressor',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Image Resizer',
    description: 'Resize images by pixels, percentage, or social media presets.',
    icon: Maximize2,
    href: '/image-resizer',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Image Cropper',
    description: 'Crop images with freeform or fixed aspect ratios — right in your browser.',
    icon: Crop,
    href: '/image-cropper',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Image Converter',
    description: 'Convert images between JPG, PNG, WebP, and BMP formats — bulk supported.',
    icon: ArrowLeftRight,
    href: '/image-converter',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Image to PDF',
    description: 'Combine multiple images into a professional PDF — drag to reorder.',
    icon: Images,
    href: '/image-to-pdf',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Watermark Image',
    description: 'Add text or image watermarks with opacity, size, and position controls.',
    icon: Stamp,
    href: '/watermark-image',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Photo Collage Maker',
    description: 'Create beautiful photo collages with multiple layouts and borders.',
    icon: LayoutGrid,
    href: '/photo-collage-maker',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Color Picker',
    description: 'Pick colors from uploaded images — get HEX, RGB, HSL, and CMYK values.',
    icon: Pipette,
    href: '/color-picker',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Blur Image',
    description: 'Blur an entire image or selected regions with adjustable intensity.',
    icon: Layers,
    href: '/blur-image',
    category: 'Image Tools',
    isNew: true,
  },
  {
    title: 'Sharpen Image',
    description: 'Enhance image sharpness with adjustable convolution enhancement.',
    icon: Focus,
    href: '/sharpen-image',
    category: 'Image Tools',
    isNew: true,
  },
  // ── Sprint 5 — Calculators ─────────────────────────────────────────────────
  {
    title: 'Calorie Calculator',
    description: 'Calculate your daily calorie needs using BMR, TDEE, and goal targets.',
    icon: Flame,
    href: '/calorie-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Body Fat Calculator',
    description: 'Estimate body fat percentage using the US Navy tape measurement method.',
    icon: Dumbbell,
    href: '/body-fat-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Pregnancy Calculator',
    description: 'Find your due date, trimester info, and days remaining from your LMP.',
    icon: Baby,
    href: '/pregnancy-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Ovulation Calculator',
    description: 'Find your fertile window and ovulation date from your last period.',
    icon: Heart,
    href: '/ovulation-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Salary Calculator',
    description: 'Convert between hourly, weekly, monthly, and annual salaries instantly.',
    icon: DollarSign,
    href: '/salary-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Tax Calculator',
    description: 'Estimate 2024 US federal income tax with bracket breakdown and effective rate.',
    icon: Landmark,
    href: '/tax-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Currency Converter',
    description: 'Convert between 30+ currencies with offline rates and comparison table.',
    icon: Coins,
    href: '/currency-converter',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Electricity Bill Calculator',
    description: 'Add appliances by wattage and hours to estimate your electricity cost.',
    icon: Lightbulb,
    href: '/electricity-bill-calculator',
    category: 'Calculators',
    isNew: true,
  },
  {
    title: 'Fuel Cost Calculator',
    description: 'Calculate trip fuel cost in imperial or metric — per mile and per km.',
    icon: Zap,
    href: '/fuel-cost-calculator',
    category: 'Calculators',
    isNew: true,
  },
  // ── Sprint 5 — Daily Life ──────────────────────────────────────────────────
  {
    title: 'Grocery List',
    description: 'Organise your grocery list by aisle, check off items, and print it.',
    icon: ShoppingBag,
    href: '/grocery-list',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Meal Planner',
    description: 'Plan breakfast, lunch, dinner, and snacks across your whole week.',
    icon: Utensils,
    href: '/meal-planner',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Weekly Planner',
    description: 'Plan your week with prioritised task lists for each day.',
    icon: CalendarDays,
    href: '/weekly-planner',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Monthly Planner',
    description: 'Full calendar grid with click-to-add notes on any day.',
    icon: Calendar,
    href: '/monthly-planner',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Daily To-Do List',
    description: 'Track tasks with High/Medium/Low priority, filter, and clear completed.',
    icon: CheckSquare,
    href: '/todo-list',
    category: 'Daily Life',
    isNew: true,
    popular: true,
  },
  {
    title: 'Shopping List',
    description: 'Add items with quantities and prices, see your estimated total.',
    icon: ListTodo,
    href: '/shopping-list',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Chore Chart Generator',
    description: 'Assign weekly chores to family members and track daily completion.',
    icon: Clipboard,
    href: '/chore-chart',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Birthday Reminder',
    description: 'Track upcoming birthdays with days-until countdown — never forget one.',
    icon: Gift,
    href: '/birthday-reminder',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Anniversary Reminder',
    description: 'Track wedding anniversaries and milestones with years elapsed.',
    icon: Heart,
    href: '/anniversary-reminder',
    category: 'Daily Life',
    isNew: true,
  },
  {
    title: 'Gift Idea Generator',
    description: 'Get curated gift ideas by age group, occasion, and budget.',
    icon: Star,
    href: '/gift-idea-generator',
    category: 'Daily Life',
    isNew: true,
  },
  // ── V2 Text Tools ──────────────────────────────────────────────────────────
  {
    title: 'Reading Time Calculator',
    description: 'Paste text to get word count, reading time, speaking time, and stats.',
    icon: BookOpen,
    href: '/reading-time-calculator',
    category: 'Text Tools',
    isNew: true,
  },
  {
    title: 'Find & Replace',
    description: 'Find and replace words or patterns in any text — with regex support.',
    icon: Replace,
    href: '/find-replace',
    category: 'Text Tools',
    isNew: true,
  },
  {
    title: 'Remove Duplicate Lines',
    description: 'Paste any list and remove duplicate lines instantly — with sort and trim options.',
    icon: Filter,
    href: '/remove-duplicates',
    category: 'Text Tools',
    isNew: true,
  },
  {
    title: 'Text Sorter',
    description: 'Sort lines A→Z, Z→A, by length, or randomly with case and numeric options.',
    icon: ArrowUpDown,
    href: '/text-sorter',
    category: 'Text Tools',
    isNew: true,
  },
  {
    title: 'Notes Pad',
    description: 'A fast multi-note notepad with colour coding, auto-save, and download.',
    icon: StickyNote,
    href: '/notes-pad',
    category: 'Text Tools',
    isNew: true,
  },
  {
    title: 'Markdown Editor',
    description: 'Write Markdown with live preview, auto-save, and export as .md or .html.',
    icon: FileText2,
    href: '/markdown-editor',
    category: 'Text Tools',
    isNew: true,
  },
  // ── V2 Developer Tools ─────────────────────────────────────────────────────
  {
    title: 'JSON Formatter',
    description: 'Format, minify, and validate JSON — with 2 or 4 space indent options.',
    icon: Code,
    href: '/json-formatter',
    category: 'Developer Tools',
    isNew: true,
  },
  {
    title: 'Base64 Encoder / Decoder',
    description: 'Encode and decode text to Base64 — with URL-safe mode support.',
    icon: Binary,
    href: '/base64',
    category: 'Developer Tools',
    isNew: true,
  },
  {
    title: 'URL Encoder / Decoder',
    description: 'Percent-encode and decode URLs — full URL or component mode.',
    icon: Link2,
    href: '/url-encoder',
    category: 'Developer Tools',
    isNew: true,
  },
  {
    title: 'Hash Generator',
    description: 'Generate SHA-1, SHA-256, SHA-384, and SHA-512 hashes using Web Crypto API.',
    icon: Shield,
    href: '/hash-generator',
    category: 'Developer Tools',
    isNew: true,
  },
  {
    title: 'UUID Generator',
    description: 'Generate up to 100 random v4 UUIDs with uppercase and curly-brace options.',
    icon: Fingerprint,
    href: '/uuid-generator',
    category: 'Developer Tools',
    isNew: true,
  },
  // ── Writing Generators ──
  { title: 'Business Name Generator', description: 'Generate unique business name ideas by industry and keywords.', icon: Briefcase, href: '/business-name-generator', category: 'Writing Generators', isNew: true },
  { title: 'Slogan Generator', description: 'Create memorable slogans for businesses and brands.', icon: Megaphone, href: '/slogan-generator', category: 'Writing Generators', isNew: true },
  { title: 'Brand Name Generator', description: 'Generate modern brand names with domain-style ideas.', icon: Sparkles, href: '/brand-name-generator', category: 'Writing Generators', isNew: true },
  { title: 'Username Generator', description: 'Create usernames based on your name, interests, or keywords.', icon: AtSign, href: '/username-generator', category: 'Writing Generators', isNew: true },
  { title: 'Mission Statement Generator', description: 'Draft a clear company mission statement in seconds.', icon: Target, href: '/mission-statement-generator', category: 'Writing Generators', isNew: true },
  { title: 'Love Letter Generator', description: 'Write a heartfelt love letter with your choice of tone.', icon: Mail, href: '/love-letter-generator', category: 'Writing Generators', isNew: true },
  { title: 'Birthday Message Generator', description: 'Craft the perfect birthday message for cards or texts.', icon: Cake, href: '/birthday-message-generator', category: 'Writing Generators', isNew: true },
  { title: 'Anniversary Message Generator', description: 'Personalized anniversary messages by years together.', icon: CalendarHeart, href: '/anniversary-message-generator', category: 'Writing Generators', isNew: true },
  { title: 'Thank You Letter Generator', description: 'Thank-you letters for gifts, help, interviews, and more.', icon: Send, href: '/thank-you-letter-generator', category: 'Writing Generators', isNew: true },
  { title: 'Apology Letter Generator', description: 'Write a sincere apology letter for any situation.', icon: Feather, href: '/apology-letter-generator', category: 'Writing Generators', isNew: true },
  // ── Fun & Lifestyle ──
  { title: 'Ask Abigail', description: 'A friendly chat companion for fun questions and inspiration.', icon: MessageCircle, href: '/ask-abigail', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Daily Fortune', description: 'Your light-hearted fortune of the day, with lucky numbers.', icon: Wand2, href: '/daily-fortune', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Random Joke Generator', description: 'Family-friendly jokes: puns, dad jokes, and one-liners.', icon: Laugh, href: '/random-joke-generator', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Word & Meaning Generator', description: 'Discover new words with meanings, examples and synonyms.', icon: BookOpen, href: '/word-meaning-generator', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Would You Rather', description: 'Endless would-you-rather questions for groups and games.', icon: Scale, href: '/would-you-rather', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Conversation Starter Generator', description: 'Great questions for dates, parties, work, and family.', icon: MessageSquare, href: '/conversation-starter-generator', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Icebreaker Questions', description: 'Icebreakers for meetings, classrooms, and workshops.', icon: Snowflake, href: '/icebreaker-questions', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Random Fact Generator', description: 'Surprising facts about science, history, space, and more.', icon: Brain, href: '/random-fact-generator', category: 'Fun & Lifestyle', isNew: true },
  { title: 'Bucket List Generator', description: 'Build your bucket list with curated adventure ideas.', icon: ListChecks, href: '/bucket-list-generator', category: 'Fun & Lifestyle', isNew: true },
  // ── Writing Generators V2 ──
  { title: 'Script Generator', description: 'Script outlines for YouTube, movies, podcasts, and plays.', icon: Clapperboard, href: '/script-generator', category: 'Writing Generators', isNew: true },
  { title: 'Speech Generator', description: 'Speeches for weddings, graduations, business, and more.', icon: Mic, href: '/speech-generator', category: 'Writing Generators', isNew: true },
  { title: 'Story Generator', description: 'Short stories from your genre, characters, and setting.', icon: BookText, href: '/story-generator', category: 'Writing Generators', isNew: true },
  { title: 'Book Outline Generator', description: 'Chapter-by-chapter outlines from your genre and premise.', icon: BookMarked, href: '/book-outline-generator', category: 'Writing Generators', isNew: true },
  { title: 'Book Chapter Generator', description: 'Chapter draft scaffolds with beats, POV, and style.', icon: BookOpen, href: '/book-chapter-generator', category: 'Writing Generators', isNew: true },
  { title: 'Dialogue Generator', description: 'Character dialogue from relationship, conflict, and tone.', icon: MessagesSquare, href: '/dialogue-generator', category: 'Writing Generators', isNew: true },
  { title: 'Essay Generator', description: 'Structured essays: argumentative, expository, and more.', icon: GraduationCap, href: '/essay-generator', category: 'Writing Generators', isNew: true },
  { title: 'Proposal Generator', description: 'Business and project proposals with scope and budget.', icon: FileSignature, href: '/proposal-generator', category: 'Writing Generators', isNew: true },
  { title: 'Press Release Generator', description: 'Standard-format press releases from your announcement.', icon: Newspaper, href: '/press-release-generator', category: 'Writing Generators', isNew: true },
  // ── Branding & Design ──
  { title: 'Logo Generator', description: 'Design a simple logo with icons, shapes, colors, and text.', icon: Palette, href: '/logo-generator', category: 'Branding & Design', isNew: true },
  { title: 'Logo Idea Generator', description: 'Logo concepts with icon, color, and typography ideas.', icon: Lightbulb, href: '/logo-idea-generator', category: 'Branding & Design', isNew: true },
  { title: 'Color Palette Generator', description: 'Harmonious color palettes with lockable swatches.', icon: Paintbrush, href: '/color-palette-generator', category: 'Branding & Design', isNew: true },
  { title: 'Font Pairing Generator', description: 'Curated heading + body font pairings with live preview.', icon: Type, href: '/font-pairing-generator', category: 'Branding & Design', isNew: true },
  { title: 'Brand Style Guide Generator', description: 'One-page brand style guide from your colors and voice.', icon: LayoutTemplate, href: '/brand-style-guide-generator', category: 'Branding & Design', isNew: true },
  { title: 'Business Card Designer', description: 'Design and download a business card from templates.', icon: Contact, href: '/business-card-designer', category: 'Branding & Design', isNew: true },
  { title: 'Flyer Generator', description: 'Event and promo flyers with templates and palettes.', icon: FileImage, href: '/flyer-generator', category: 'Branding & Design', isNew: true },
  { title: 'Poster Generator', description: 'Bold typographic posters, ready to download as PNG.', icon: ImagePlus, href: '/poster-generator', category: 'Branding & Design', isNew: true },
  { title: 'Banner Creator', description: 'Banners in preset sizes for web and social covers.', icon: PanelTop, href: '/banner-creator', category: 'Branding & Design', isNew: true },
  { title: 'Social Media Brand Kit', description: 'Matching avatar, cover, and post templates for socials.', icon: Share2, href: '/social-media-brand-kit', category: 'Branding & Design', isNew: true },
  // ── Marketing Tools ──
  { title: 'Product Name Generator', description: 'Catchy product name ideas from category and keywords.', icon: Package, href: '/product-name-generator', category: 'Marketing Tools', isNew: true },
  { title: 'Ad Copy Generator', description: 'Platform-aware ad headlines and body copy variants.', icon: Megaphone, href: '/ad-copy-generator', category: 'Marketing Tools', isNew: true },
  { title: 'Email Subject Line Generator', description: 'Subject line variants with character counts.', icon: MailOpen, href: '/email-subject-line-generator', category: 'Marketing Tools', isNew: true },
  { title: 'Call-to-Action Generator', description: 'CTA button text and supporting copy for any goal.', icon: MousePointerClick, href: '/cta-generator', category: 'Marketing Tools', isNew: true },
  { title: 'Marketing Plan Generator', description: 'Structured plan with goals, channels, timeline, KPIs.', icon: ClipboardList, href: '/marketing-plan-generator', category: 'Marketing Tools', isNew: true },
  { title: 'Content Calendar Generator', description: 'A 4-week content calendar of post ideas per platform.', icon: CalendarRange, href: '/content-calendar-generator', category: 'Marketing Tools', isNew: true },
  { title: 'Product Description Generator', description: 'Benefit-driven product descriptions in your tone.', icon: PenLine, href: '/product-description-generator', category: 'Marketing Tools', isNew: true },
  // ── Utility V2 ──
  { title: 'QR Scanner', description: 'Scan QR codes with your device camera — fully private.', icon: ScanLine, href: '/qr-scanner', category: 'Utility Tools', isNew: true, tags: ['qr', 'qrcode', 'scan', 'camera', 'reader'] },
  { title: 'Barcode Generator', description: 'Generate CODE128, EAN-13, UPC, and CODE39 barcodes.', icon: Barcode, href: '/barcode-generator', category: 'Utility Tools', isNew: true, tags: ['barcode', 'qr', 'ean', 'upc', 'code128', 'scan', 'generator'] },
  { title: 'Barcode Scanner', description: 'Scan product barcodes with your camera, offline.', icon: ScanBarcode, href: '/barcode-scanner', category: 'Utility Tools', isNew: true, tags: ['barcode', 'scan', 'camera', 'qr', 'reader'] },
  { title: 'Signature Generator', description: 'Typed signature styles in cursive fonts, PNG download.', icon: PenTool, href: '/signature-generator', category: 'Utility Tools', isNew: true, tags: ['signature', 'sign', 'cursive', 'handwriting', 'generator'] },
  { title: 'Digital Signature Creator', description: 'Draw your signature and download a transparent PNG.', icon: Pen, href: '/digital-signature-creator', category: 'Utility Tools', isNew: true, tags: ['signature', 'sign', 'draw', 'handwriting', 'esign'] },
  { title: 'Invoice Number Generator', description: 'Sequential invoice numbers with custom prefix format.', icon: Hash, href: '/invoice-number-generator', category: 'Utility Tools', isNew: true },
  { title: 'Password Strength Checker', description: 'Check password strength and crack time — private.', icon: ShieldCheck, href: '/password-strength-checker', category: 'Utility Tools', isNew: true },
  { title: 'File Checksum Generator', description: 'MD5, SHA-1, and SHA-256 checksums for any file.', icon: FileCheck, href: '/file-checksum-generator', category: 'Utility Tools', isNew: true },
  // ── Professional & Identity ──
  { title: 'ID Card Generator', description: 'Employee, student, visitor and event ID cards with photo, QR code and barcode.', icon: CreditCard, href: '/id-card-generator', category: 'Branding & Design', isNew: true, tags: ['id', 'identity', 'badge', 'employee id', 'student id', 'event pass', 'qr', 'barcode', 'generator'] },
  { title: 'Email Signature Generator', description: 'Generate professional HTML email signatures for Gmail, Outlook and Apple Mail.', icon: AtSign, href: '/email-signature-generator', category: 'Branding & Design', isNew: true, tags: ['email', 'signature', 'gmail', 'outlook', 'html', 'generator'] },
  { title: 'Cover Letter Generator', description: 'Professional cover letters in formal, modern, and creative styles. Export to PDF.', icon: FileSignature, href: '/cover-letter-generator', category: 'Writing Generators', isNew: true, tags: ['cover letter', 'resume', 'cv', 'job application', 'career', 'pdf', 'generator'] },
  { title: 'Passport Photo Maker', description: 'Resize and crop photos to passport standards for US, UK, EU, India and more.', icon: ScanLine, href: '/passport-photo-maker', category: 'Image Tools', isNew: true, tags: ['passport', 'photo', 'id photo', 'visa', 'crop', 'resize'] },
  { title: 'Appointment Card Generator', description: 'Hospital, salon, clinic and business appointment cards with QR code.', icon: CalendarRange, href: '/appointment-card-generator', category: 'Branding & Design', isNew: true, tags: ['appointment', 'booking', 'qr', 'salon', 'clinic', 'hospital', 'card', 'generator'] },
  { title: 'Shipping Label Generator', description: 'Shipping labels with sender, receiver, barcode and tracking number. Print-ready.', icon: Package, href: '/shipping-label-generator', category: 'Utility Tools', isNew: true, tags: ['shipping', 'label', 'barcode', 'qr', 'tracking', 'package', 'generator'] },
];

// ─── Category config ──────────────────────────────────────────────────────────

export const CATEGORIES: { name: Category; emoji: string; color: string; bg: string; border: string }[] = [
  { name: 'Text Tools',      emoji: '📄', color: 'text-violet-700', bg: 'bg-violet-50',  border: 'border-violet-100' },
  { name: 'Calculators',     emoji: '🧮', color: 'text-emerald-700', bg: 'bg-emerald-50', border: 'border-emerald-100' },
  { name: 'Daily Life',      emoji: '🏠', color: 'text-teal-700',   bg: 'bg-teal-50',    border: 'border-teal-100' },
  { name: 'Utility Tools',   emoji: '🔧', color: 'text-blue-700',   bg: 'bg-blue-50',    border: 'border-blue-100' },
  { name: 'Developer Tools', emoji: '💻', color: 'text-orange-700', bg: 'bg-orange-50',  border: 'border-orange-100' },
  { name: 'PDF Tools',       emoji: '📑', color: 'text-red-700',    bg: 'bg-red-50',     border: 'border-red-100' },
  { name: 'Image Tools',     emoji: '🖼️', color: 'text-pink-700',   bg: 'bg-pink-50',    border: 'border-pink-100' },
  { name: 'Writing Generators', emoji: '✍️', color: 'text-indigo-700', bg: 'bg-indigo-50',  border: 'border-indigo-100' },
  { name: 'Branding & Design',  emoji: '🎨', color: 'text-fuchsia-700', bg: 'bg-fuchsia-50', border: 'border-fuchsia-100' },
  { name: 'Marketing Tools',    emoji: '📢', color: 'text-cyan-700',    bg: 'bg-cyan-50',    border: 'border-cyan-100' },
  { name: 'Fun & Lifestyle',    emoji: '🎉', color: 'text-amber-700',  bg: 'bg-amber-50',   border: 'border-amber-100' },
];

    // ─── Helpers ────────────────────────────────────────────────────────────────

    export function getToolByHref(href: string): Tool | undefined {
    return TOOLS.find((t) => t.href === href);
    }

    export function getRelatedTools(href: string, count = 4): Tool[] {
    const tool = getToolByHref(href);
    if (!tool) return TOOLS.slice(0, count);
    const sameCat = TOOLS.filter((t) => t.category === tool.category && t.href !== href);
    const others = TOOLS.filter((t) => t.category !== tool.category && t.href !== href);
    return [...sameCat, ...others].slice(0, count);
    }
    